### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by aydeaver** [mrcomac/enhancedcombathud-swade#1]
Cloned your repo to test the HUD and got this:
`Metadata validation failed for module "enhancedcombathud-swade": The file "dist/argo-swade.min.js" included by module enhancedcombathud-swade does not exist`

I do have Argon Combat HUD (CORE) installed.

**Comment by mrcomac** [comment]
Hi @aydeaver 
You can install from the link below
https://github.com/mrcomac/enhancedcombathud-swade/releases/download/0.0.3/module.json
