### ISSUE TITLE
Status Icon

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#10]
Hi. Can you replace the status icon?
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/18772792-31ff-413d-bf7e-1251b449d03a)

**Comment by mrcomac** [comment]
ditto #11

**Comment by brunocalado** [comment]
> ditto #11

icons/skills/toxins

**Comment by mrcomac** [comment]
featured: https://github.com/mrcomac/enhancedcombathud-swade/releases/tag/0.0.8
