### ISSUE TITLE
Icon for Actions

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#11]
I think this exclamation icon could be a better option to the action icon

![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/18591dae-c04b-4ae3-8083-7b8161b27f36)

**Comment by mrcomac** [comment]
are these icons from SUCC?

**Comment by brunocalado** [comment]
> are these icons from SUCC?

They are at: 
icons/sundries/books

**Comment by mrcomac** [comment]
featured: https://github.com/mrcomac/enhancedcombathud-swade/releases/tag/0.0.8
