### ISSUE TITLE
Status Not Working with SUCC

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#13]
When I click at a condition I receive the error:
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/dcaeb8f4-412e-4dd7-846d-319dfa8446b0)

**Comment by mrcomac** [comment]
featured: https://github.com/mrcomac/enhancedcombathud-swade/releases/tag/0.0.8
