### ISSUE TITLE
Visual error when expanding a die roll

### ISSUE THREAD

**Issue by senatorhatty** [mrcomac/enhancedcombathud-swade#14]
When using Argon Combat HUD with Savage Worlds and expanding a roll in the chat, the display of the dice is messed up, crossing other text and becoming hard to read. This happens when only Argon Core and SWADE (along with lib-color settings) are enabled.
![SCR-20240406-pgi](https://github.com/mrcomac/enhancedcombathud-swade/assets/8930477/89b15002-a910-49fe-bbd1-774f8cf4100d)

Core Version: Version 11 Stable, 11.315
System: swade, 3.3.10
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
GPU: ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Unspecified Version)
Module Count: 4
Argon - Combat HUD (CORE): 2.5.12
lib - Color Settings: 3.0.2

**Comment by mrcomac** [comment]
https://github.com/mrcomac/enhancedcombathud-swade/releases/tag/0.0.9
