### ISSUE TITLE
Incompatibility with the module "SWADE Ultimate Condition Changer" 

### ISSUE THREAD

**Issue by peterprokurist** [mrcomac/enhancedcombathud-swade#17]
The HUD stops working as soon as I activate the module: "SWADE Ultimate Condition Changer (SUCC)".
SUCC is important for the module: "Better Rolls 2 for Savage Worlds" (one of my favorite modules for SWADE).

Foundry:  V12.328
SWADE:  V4.0.3
SUCC:  V3.3.2
Better Rolls:  4.1

**Comment by mrcomac** [comment]
Hi @peterprokurist 
Sorry the delayed response.
I don't use br2 for swade anymore and forgot to test it :/
Will work on it soon (this week)

Cheers

**Comment by mrcomac** [comment]
solved in 1.0.1
