### ISSUE TITLE
Boost / trait Lower

### ISSUE THREAD

**Issue by jasharen** [mrcomac/enhancedcombathud-swade#19]
Using SUCC 4.0.0 in combination with the latest version of Enhanced Combat Hud (Agron HUD) I attempt to raise or lower trait as an effect, and nothing happens. The below error message occurs in the console on line 55 of agro-swade.min.js.

If I click the status from the token, everything works properly. 

![image](https://github.com/user-attachments/assets/1fadb3d7-16e4-4ff6-8efe-160e5e0adec0)

**Comment by mrcomac** [comment]
can you please share the effect's name?

**Comment by jasharen** [comment]
Doing a full review of all status' and the following do not appear to be handled the same way as when interacting with the token directly.
"warrior's-gift"
"wound"
"fatigue"
'boost-trait'
'lower-trait'
'cover-- shield'
'defeated'
'rage'

That seems to be an exhaustive list. I tried applying all status' both through the token and through the HUD, and those are the ones that errored via the HUD.

Thanks!!

**Comment by mrcomac** [comment]
Thank you @jasharen for that list.

I opened a issue to SUCC to ask some help on how to implement this.

**Comment by mrcomac** [comment]
it's sorted out. next release should address this issue.
