### ISSUE TITLE
Feature Request: Highlight active status

### ISSUE THREAD

**Issue by jasharen** [mrcomac/enhancedcombathud-swade#20]
I'm not sure if this is the correct process to make a feature request. If not or if it is just not possible, please let me know.

It would be amazing if the Status button highlighted active status on a token in the HUD.
Example below has several of the status effects currently active on the token, but there is no easy way to tell that without going to the token itself.

If it could be highlighted the same way as the mouse hover effect, or maybe an outline around the active effect that would be an amazing improvement.

Thanks!

![image](https://github.com/user-attachments/assets/45026ad6-a035-404f-93be-19c95bc41c49)

**Comment by mrcomac** [comment]
this is not supported by the Argo Core and it will not be implemented by the Core. Reference: https://discord.com/channels/844900867240361984/1022176441900740730/1271016799944573018
i'll work on a way within this package (swade one).

**Comment by mrcomac** [comment]
next release will contain a hightligh to the current statuses for an actor.
