### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#3]
Can you make the icons from SUCC show up?

![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/f1bd6d60-5f0a-4b25-af40-df53d4864927)

**Comment by mrcomac** [comment]
The item icons are from the item itself. As soon as you update the items with the SUCC icons, they will show up.
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/6748594/8a7f14f6-a37f-4217-be7e-8c67dca7ef2c)

**Comment by brunocalado** [comment]
Eu não entendi. O que tenho que fazer?

**Comment by mrcomac** [comment]
Before enable SUCC
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/6748594/20ce6bd5-fb7b-4434-9449-67bde904acb6)

After enable SUCC
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/6748594/511256e2-2514-4247-b074-7eb831bf5e3c)
