### ISSUE TITLE
Improve Reading

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#5]
Hi.

It's hard to read the text. Can you improve that?
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/1f4dd220-5b95-4247-8529-eb2637986dfa)

**Comment by mrcomac** [comment]
I've changed the bg's alpha.

![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/6748594/bd6694f9-be13-4c73-bd50-84fa029e79ea)

did it improve?

**Comment by brunocalado** [comment]
> I've changed the bg's alpha.
> 
> ![image](https://private-user-images.githubusercontent.com/6748594/320988463-bd6694f9-be13-4c73-bd50-84fa029e79ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjY0MzAsIm5iZiI6MTcxMjg2NjEzMCwicGF0aCI6Ii82NzQ4NTk0LzMyMDk4ODQ2My1iZDY2OTRmOS1iZTEzLTRjNzMtYmQ1MC04NGZhMDI5ZTc5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMjAwODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM4Y2FmODhjMDQwZmIxY2M0Mjg2ZDU0YzRmYmFiZmRmNjNlODExYTY3OTRlNDY4NzgyNmFjYWVkN2NmZTdkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QE8wX5tHnHsGABpyJ_zg39PrWdWOIjo45aZA4tk_eNI)
> 
> did it improve?

Thks. It's good.
