### ISSUE TITLE
Improve Run Icon

### ISSUE THREAD

**Issue by brunocalado** [mrcomac/enhancedcombathud-swade#8]
Hi

Can you change the run icon for something with a better looking?
![image](https://github.com/mrcomac/enhancedcombathud-swade/assets/4999783/ce39df7b-4fbc-4d4b-ba06-d9c82f0b66c7)

**Comment by mrcomac** [comment]
featured: https://github.com/mrcomac/enhancedcombathud-swade/releases/tag/0.0.8
